<?php

namespace App\Controllers;
use App\Models\SubcontractorModel;
use App\Models\ClientModel;

class Subcontractor extends BaseController
{
	public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger){
		// Do Not Edit This Line
		parent::initController($request, $response, $logger);
		header("Access-Control-Allow-Origin: * ");
		header("Access-Control-Allow-Methods: *");
		header("Access-Control-Allow-Headers: * ");
        $this->model = new SubcontractorModel();
        $this->model = new ClientModel();
   
	}
	function __construct(){
                    
        helper(['url', 'form']);          
     }

	public function index()
	{
	//	echo view('admin/add_user_form');
	
   	     //$session=session();
		// if($session->has('admin'))
		// {
			
		// 
        
        return view('main_content');
		

	} 
    public function getclient()
    {
      
      print_r($data); exit;
    }

    public function sub_add()
	{	
        //  $cnt=new ClientModel();  
        // $data['sub_details']=$cnt->table("client")->findall();

        $data=array();  
		$SubcontractorModel = new SubcontractorModel();
        $dataArr['sub_details'] = $SubcontractorModel->getclientData();
        											     
		echo view('admin/subcontractor/subadd',$dataArr);
	}

   
    public function sub_insert()
    {
$validation_msg=$this->validate([
    'subcompanyName'=>'required',
    'ownername'=>'required',
    'cellno'=>'required',
      // 'company_address'=>'required'
],
[
  
     'subcompanyName'=>['required'=>'Sub Contractor Comapny Name Is Required...'],
      'ownername'=>['required'=>'Sub Contractor Owner Name Is Required...'],
        'cellno'=>['required'=>'Sub Contractor cell Number Is Required...']
     
]);
if(!$validation_msg)
{
    $errors_msg['error']=$this->validation->getErrors();
    $data=array();  
    $SubcontractorModel = new SubcontractorModel();
    $errors_msg['sub_details'] = $SubcontractorModel->getclientData();
    return view('admin/subcontractor/subadd',$errors_msg);

}else {



                $cnt=new SubcontractorModel();
                        /** this code project autogenerated id in serial number
                  * Authur : Bhushan G Salunkhe
                 */
               $data['lastID'] = $cnt->fetchLastInsertedIDSub();
            
               $arrLastid = array();
               if(!empty($data['lastID']))
               {  
                   $j=0;
        
                while($data['lastID'][0]->sub_no > $j)
                 {
                   $j =  $data['lastID'][0]->sub_no + 1 ;
                   $arrLastid['sub_no'] = $j ;
                   $j++;
                 }
               }else
               {  
                $j= 1;
                 $arrLastid['sub_no'] = $j ;
               }

                $data=[
                     'sub_no'=>$arrLastid['sub_no'],
                     'sub_company_name'=>$this->request->getPost('subcompanyName'),
                     'sub_owner_name'=>$this->request->getPost('ownername'),
                     'sub_cell_no'=>$this->request->getPost('cellno'),
                    'sub_email'=>$this->request->getPost('subemail'),
                    'sub_contact_person'=>$this->request->getPost('sub_con_per_name'),
                    'sub_contact_cell_no'=>$this->request->getPost('Sub_con_per_cellno'),
                    'sub_contact_email'=>$this->request->getPost('sub_con_per_email'),
                    'activity1'=>$this->request->getPost('activity1'),
                    'activity2'=>$this->request->getPost('activity2'),
                    'activity3'=>$this->request->getPost('activity3'),
                    'activity4'=>$this->request->getPost('activity4'),
                    'created_at'=>date('Y-m-d H:i:s'),
                ];
                // print_r($data); exit;
                $cnt->insert($data);
				//  print_r($data); 
            }

			  $session = session();
			$this->session->setFlashdata('success','Sub Contractor Record insert succesfully');
            return redirect('Sub/sub_form');
                            
    }
    public function sub_form()
	{		
        $SubcontractorModel = new SubcontractorModel();    
        $data['emp']=$SubcontractorModel->fetch_cllientSubcontactor();   
        // $data['emp']=$cnt->findall();
		echo view('admin/subcontractor/subshow',$data);
	}
  
    public function sub_profile($id)
    {

        $SubcontractorModel = new SubcontractorModel(); 
        // $data['sub_profile']=$sub->find();
        $data['sub_profile']=$SubcontractorModel->fetch_Profile($id);   		
        echo view('admin/subcontractor/sub_profile',$data);
    
    }
  //'picture'=>['required'=>'First Shop Name Required...'
// 'exact_length[10]'=>'Mobile nimber must be a  digit.'
    

    public function delete($id)
    {
        $cnt = new SubcontractorModel();
        $cnt->where('sub_id',$id)->delete();
        $session = session();
		$session->setFlashdata('success','Sub Contractor record delete succesfully');
        return redirect('Sub/sub_form');

    }
    public function edit($id)
    {
        $cnt = new SubcontractorModel();
        $dataArr['row']=$cnt->where('sub_id',$id)->first();
         //$cnt_id = $dataArr['row']['cnt_id'];
        return view('admin/subcontractor/subedit',$dataArr);
    }


    // $cnt = new SubcontractorModel();
    // $dataArr['row']=$cnt->where('sub_id',$id)->first();
    // $SubcontractorModel = new SubcontractorModel();
    // $dataArr['sub_details'] = $SubcontractorModel->getclientData();

    // return view('admin/subcontractor/subedit',$dataArr);

    public function update($id)
    {
        
            
        $cnt=new SubcontractorModel();   
        $cnt->find($id);   											     
        $data=[
            'sub_no'=>$this->request->getPost('subcontractorno'),
            'sub_company_name'=>$this->request->getPost('companyname'),
             'sub_owner_name'=>$this->request->getPost('ownername'),
            'sub_cell_no'=>$this->request->getPost('cellno'),
            'sub_email'=>$this->request->getPost('subemail'),
            'sub_contact_person'=>$this->request->getPost('sub_con_per_name'),
            'sub_contact_cell_no'=>$this->request->getPost('Sub_con_per_cellno'),
            'sub_contact_email'=>$this->request->getPost('sub_con_per_email'),
            'activity1'=>$this->request->getPost('activity1'),
                    'activity2'=>$this->request->getPost('activity2'),
                    'activity3'=>$this->request->getPost('activity3'),
                    'activity4'=>$this->request->getPost('activity4'),
            'updated_by'=>date('Y-m-d H:i:s'),
        ];
        
        $cnt->update($id,$data); 
        //  print_r($data); 
    
       
        //  print_r($data); 
            
				$session = session();
				$session->setFlashdata('success','Sub Contractor Data update succesfully');
            //    $data['action']=BASE('Usercontroller/update'.$id);
            return redirect('Sub/sub_form');
                 
    }


    /*Code Author : 
Code Description: ajax call for selected dropdown to put their value in textbox   */
	public function selectedClient()
	{
		
	    if($_POST['post_id'])
      {
		$id=$_POST['post_id'];

        $SubcontractorModel = new SubcontractorModel();    
        $dataArr['ajaxClientDetails'] = $SubcontractorModel->getSubcontractor($id);
		echo json_encode($dataArr);
	
	  }
      
	}



}

